version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: property_postgres
    restart: always
    environment:
      POSTGRES_DB: property_db
      POSTGRES_USER: property_user
      POSTGRES_PASSWORD: property_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: property_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data  # Added persistent Redis volume

volumes:
  postgres_data:
  redis_data:
